export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const SET_PAGINATION_POkEMONS = 'SET_PAGINATION_POkEMONS';
export const SET_PAGINATION_BERRIES = 'SET_PAGINATION_BERRIES';
export const SET_LOADING_BERRIES = 'SET_LOADING_BERRIES';
export const SET_LOADING_POKEMONS = 'SET_LOADING_POKEMONS';
export const GET_BERRIES = 'GET_BERRIES';
